### ISSUE TITLE
Can't login via Google+

### ISSUE THREAD

**Issue by Bengt** [zealot128/podfilter#12]
The Google+ login seems to be broken somehow. When I click the link to <http://www.podfilter.de/auth/gplus>, I get the following error:

```
400. That’s an error.

Error: redirect_uri_mismatch

Application: Podfilter.de

You can email the developer of this application at: stwienert@gmail.com

The redirect URI in the request: https://www.podfilter.de/auth/gplus/callback did not match a registered redirect URI.

Learn more

Request Details
hl=de
scope=https://www.googleapis.com/auth/userinfo.email
response_type=code
redirect_uri=https://www.podfilter.de/auth/gplus/callback
state=bf2368b8679f7981f6daedc7752ec95957ce3b0cc3e33ed0
client_id=251667415729.apps.googleusercontent.com
That’s all we know.
```

This hints at a misconfigured redirect URI in the Developers Console. When I open <https://podfilter.de> in an incognito tab and log in manually, I get the same result.

I authorized podfilter at Dezember 23rd, 2014. When I remove the permission at <https://security.google.com/settings/security/permissions> and try to login via podfilter again, I also get the same error.

When i manually open [the redirect URI](https://www.podfilter.de/auth/gplus/callbackstate=8316e4b348bf0d30769a6c38683d4ce0d7f7f3e9cc4bc24fclient_id=251667415729.apps.googleusercontent.com), I get the following error:

```
The page you were looking for doesn't exist.

You may have mistyped the address or the page may have moved.

If you are the application owner check the logs for more information.
```

So the redirect URI might have actually changed. I was able to use the google plus signin a few weeks ago.

**Comment by zealot128** [comment]
Ok, since I added Letsencrypt's SSL certs and forced SSL, the redirect URIs must change, too. I've changed G+ now.

**Comment by Bengt** [comment]
Logging in via Google+ still does not work for me, somehow. I tried deactvitating the adblocker, but that did not help.

**Comment by zealot128** [comment]
OK. I fixed it now. There was a problem in a recently upgraded dependency (omniauth-oauth2 gem), which broke FB & G+ Login.

thanks for reporting!

**Comment by Bengt** [comment]
Awesome, finally I can access my old list again. Thanks!
