### ISSUE TITLE
Let users opt in to anonymized publication in a downloadable dataset

### ISSUE THREAD

**Issue by astro** [zealot128/podfilter#2]
Please let other hackers play with your recommendation engine challenges. :-)

**Comment by zealot128** [comment]
@astro nach einer Diskussion auf [sendegate](https://sendegate.de/t/netzwerkstudie-zur-podcasthoererschaft/1556) gibt es nun endlich eine erste Schnittstelle:

http://www.podfilter.de/api/v1/subscribers/flat_subscriptions.json?api_key=...
Zurueck kommt dann sowas wie:


       [
         { owner_id: 123123123, podcast_id: 12, podcast_title: "", podcast_categories: [] },
         ...
       ]

Api-Key gibts automatisch fuer jeden Nutzer (nach dem Einloggen ganz unten).
Nutzer-IDs sind sowieso auto-generated und werden nirgends auf der Seite in URLs verwendet, d.h. pseudonym.

**Comment by astro** [comment]
Hey, cool!
