### ISSUE TITLE
Feature Request / Idea: Share my podcast list

### ISSUE THREAD

**Issue by funkenstrahlen** [zealot128/podfilter#7]
I would really love to have the possibility to share my podcast list with others. Podfilter has all ressources to do this.

Scenario:

1. Upload OPML (or create list by hand)
2. Get a nice list of all the podcasts (coverart, name, podlove subscribe button)
3. Get an url to that list which can then be shared via social network

**Comment by zealot128** [comment]
What do you miss to to this? you can upload an OPML from the frontpage. This opml gets a quasi random string-id which then can be sent to other people, too.

**Comment by i42n** [comment]
Podfilter only shows recommended Podcasts based on my opml. It does not list the podcasts in my opml.

**Comment by funkenstrahlen** [comment]
I just found a the correct way to achieve exactly what I wanted. You were right, it is already implemented. Thank you so much for you great work!
