### ISSUE TITLE
Add podlove subscribe button

### ISSUE THREAD

**Issue by i42n** [zealot128/podfilter#8]
I think it would be very nice to have the podlove subscribe button instead of all the feed urls listed. Better overview and smoother UX.

**Comment by zealot128** [comment]
Thanks for the feedback. I've bundled the Podlove assets and added a subscribe button to the podcast show pages.
The subscribe button from Podfilter is still there, because otherwise Podfilter can't recalculate new podcast recommendations based upon the new profile.

**Comment by i42n** [comment]
Thanks!
