### ISSUE TITLE
New Feature / Revert: Show All Episodes

### ISSUE THREAD

**Issue by h45rd** [zealot128/podfilter#9]
Hi,

Zunächst: Danke für das tolle Projekt!

Bei Podcasts mit hoher Episodenfrequenz (beispielsweise SWR1 Leute), welchen man aber nur passiv folgt, war Podfilter bis zu Commit https://github.com/zealot128/podfilter/commit/f87d83bbf580a3b371bd1d0506420a09b9abccae klasse als Archiv zum turnusmäßigen Massendownload nutzbar.

Wäre es möglich eine "Show All Episodes" oder "Show Next 100 Episodes" Funktion zu implementieren?

Gruß,
Harald

**Comment by zealot128** [comment]
Hallo Harald,
eine Limitierung war notwendig da es 1-2 Podcasts gibt mit mehreren 1000 Episoden - Jeder Besucher einer solchen Seite riskiert dass sein Browser eingefroren wird und u.U. abstuerzt.

Ich habe entsprechende Naechste/Vorherige Seite Links mit eingebaut. Damit kannst du alle Episodes durchgehen.

BG Stefan

**Comment by h45rd** [comment]
Hallo Stefan,

Super! Ich danke Dir vielmals :)

Gruß,
Harald
